language: php

php:
  - 5.6
  - 7.0
  - 7.1.9
  - 7.2

before_script:
  - composer self-update
  - composer --version
  - composer install --prefer-dist --no-interaction

script: ./vendor/bin/phpunit
